# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a slim Python base image
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY README.md .
COPY README_es.md .
COPY .env .
COPY LICENSE .
COPY src/ src/

# Install Python dependencies and package
RUN pip install --no-cache-dir .

# Default command: start the MCP server using the entrypoint
CMD ["aemet_mcp"]
